### ISSUE TITLE
Developing Wireframes

### ISSUE THREAD

**Issue by DDeviak** [2024-Software-Engineering-Pmi-32/LambdaChess-docs#9]
**Description**: Design wireframes for the main screens of the LambdaChess application, including the main menu, game screen, profile page, and settings.

- Create wireframes for:
  - Main Menu
  - Game Screen
  - Profile Page
  - Settings

**Acceptance Criteria**:
- Wireframes are created using Balsamiq or a similar tool.
- All key elements are included: navigation, buttons, user interactions.
- Wireframes are uploaded to the GitHub repository.

**Comment by RomaB-5** [comment]
https://www.figma.com/proto/RZ43FtW6K6b01xlkOOs4je/Untitled?node-id=0-1&node-type=canvas&t=rSq5uG59EFATb6Hf-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=10%3A155
